name: free_scroll
description: "A unique Flutter package that enables 4-dimensional scrolling and zooming of widgets within a constrained area, with no similar package available in the Flutter ecosystem."
version: 1.0.8
homepage: https://github.com/fazil-kp/free_scroll.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
